name: Build & Code Quality Checks
on:
  push:
    branches: [main]

jobs:
  build:
    name: Build & Code Quality Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - run: yarn run check
      - run: yarn run check-code-formatting
      - run: yarn run build
